### PR TITLE
Migrate Vagrant VM to use Homestead

### PR DESCRIPTION
**Pull request by ericpoe**
Since we are already using Vagrant on building the joindin VM for devs, I wanted to continue to use Vagrant for upgrading our dev environment from PHP 5.6 to PHP 7.3. Eventually, I'd like to migrate away from Vagrant to using smaller containers via Docker or similar; but for now, let's continue using Vagrant since it has a proven track record with this project.

## TODO

- [x] Update documentation (will also take care of #94)
- [x] Install xdebug
- [x] Install Wireshark
- [x] Fix http://legacy.dev.joind.in, most likely by removing it since it is going away soon

## Requirements

- Vagrant
- Vagrant plugins (install via `vagrant plugin install vagrant-name-of-plugin`):
  - vagrant-hostsupdater
- VirtualBox, VMWare, or Parallels

## Installation

- `composer install`
- `vendor/bin/homestead make`
- make any necessary changes to `Homestead.yaml` for your dev box (ex. change the provider from "virtualbox" to "vmware"
- Launch the new VM environment: `vagrant up`

### CODE REVIEW

**Comment by heiglandreas** [comment]
Having the possibility to have a "golden master" to take with us to hackatons and such would make setup on such events much easier and especially WiFi-friendly. Composer still needs to run locally but that should not be an issue....

So from me +1 for a "Golden Master"

**Comment by heiglandreas** [comment]
And I'd not include legacy any more. We are going to shut it down, so we should not invest time into getting it up and running on the new dev-setup.
When someone enters "legacy.dev.joind.in" they should be either redirected to https://joind.in or just see an error page like you would for any other non existing subdomain...(My 0.02 €)

**Comment by ericpoe** [comment]
@heiglandreas Now to figure out how to create a "golden master" that is Homestead-friendly :)

**Comment by svpernova09** [comment]
FYI We shouldn't reccomend the vbguest plugin by default. Homestead boxes are always built with the latest version of a provider at the time. Meaning if Virtualbox's guest additions are higher *in the box* than on your computer: You should upgrade Virtualbox.If VIrtualbox's guest additions are higher *on your computer* than in the box: You may want to downgrade if you see issues.

**Comment by svpernova09** [comment]
Do we need Elasticsearch? I'm not sure if/where we're using it today. Any ideas @heiglandreas?

**Comment by heiglandreas** [comment]
Currently there is no elasticsearch used in joind. in. Or at least I never have seen it. And IMO it adds a layer of complexity that is currently not really needed. So I'd leave it out 😉

**Comment by svpernova09** [comment]
@ericpoe Can we get another todo list for this? Do you and I need to walk through this together? I think outside of documentation it should be really close.

**Comment by ericpoe** [comment]
@heiglandreas Once this PR is merged in, I'll create a ticket to find a way to create a portable 'golden master' for use at hackathons, workshops, etc.

**Comment by ericpoe** [comment]
Thank you!

**Pull request merged**
